version: "3"
services:


  cherry-runtime:
    image: "zeebe-cherry-simpleexample:1.0.0"
    container_name: "Cherry-Simple-Example"
    ports:
      - "9091:9091"
    environment:
      - ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS=host.docker.internal:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
      - ZEEBE_CLIENT_CLOUD_REGION=
      - ZEEBE_CLIENT_CLOUD_CLUSTERID=
      - ZEEBE_CLIENT_CLOUD_CLIENTID=
      - ZEEBE_CLIENT_CLOUD_CLIENTSECRET=
      - LOGGING_LEVEL_ROOT=INFO
